# Generated by Django 3.1.3 on 2020-11-26 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0002_auto_20201126_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='highest_bid_id',
        ),
    ]
