# Generated by Django 3.1.3 on 2020-11-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0004_auto_20201126_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher',
                                              to='auctions.auctionlisting')),
                ('watcher',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_listings',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
