# Generated by Django 3.1.3 on 2020-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0006_auto_20201126_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
