# Generated by Django 3.1.3 on 2020-12-02 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auctions', '0007_auctionlisting_starting_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='starting_bid',
            new_name='highest_bid',
        ),
    ]
